package app.schedula.ui.navigation

object Routes {
    const val LOGIN = "login"
    const val OTP = "otp"
    const val MAIN = "main"
    const val DOCTORS = "doctors"
    const val RECORDS = "records"
    const val APPOINTMENTS = "appointments"
    const val PROFILE = "profile"
    const val DOCTOR_DETAILS = "doctor_details"
    const val BOOKING = "booking"
    const val CONFIRMATION = "confirmation"
    const val APPOINTMENT_DETAILS = "appointment_details"
    const val RECORD_DETAILS = "record_details"
    const val SLOT_UNAVAILABLE = "slot_unavailable"
    const val PATIENT_DETAILS = "patient_details"
    const val CANCEL_APPOINTMENT = "cancel_appointment"
    const val PERSONAL_INFO = "personal_info"
    const val FAMILY_MEMBERS = "family_members"
    const val SUPPORT = "support"
    const val SELECT_PATIENT = "select_patient"
    const val PAYMENT = "payment"
    const val DOCTOR_HISTORY = "doctor_history"
    const val DOCTOR_DASHBOARD = "doctor_dashboard"
    const val DOCTOR_PROFILE = "doctor_profile"

    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val ADD_DOCTOR = "add_doctor"
    const val MANAGE_DOCTORS = "manage_doctors"
    const val ADMIN_APPOINTMENTS = "admin_appointments"

    const val EDIT_DOCTOR = "edit_doctor"
    const val DOCTOR_SCHEDULE = "doctor_schedule"
}
